/// Generated by AssetsRefGenerator on 2021/03/23
class Res {
  static const String gender_arrow = "images/gender_arrow.svg";
  static const String gender_female = "images/gender_female.svg";
  static const String gender_male = "images/gender_male.svg";
  static const String gender_other = "images/gender_other.svg";
  static const String pacman = "images/pacman.svg";
  static const String person = "images/person.svg";
  static const String user = "images/user.svg";
  static const String weight_arrow = "images/weight_arrow.svg";
}
