/// Generated by AssetsRefGenerator on 2021/04/09
class Res {
  static const String home = "assets/animations/home.json";
  static const String onboarding_animation = "assets/animations/onboarding_animation.json";
  static const String travel_tickets = "assets/animations/travel_tickets.json";
}
