/// Generated by AssetsRefGenerator on 2021/04/01
class Res {
  static const String agile_fly_1 = "assets/images/agile-fly-1.png";
  static const String agile_fly_2 = "assets/images/agile-fly-2.png";
  static const String agile_fly_dead = "assets/images/agile-fly-dead.png";
  static const String backyard = "assets/images/backyard.png";
  static const String drooler_fly_1 = "assets/images/drooler-fly-1.png";
  static const String drooler_fly_2 = "assets/images/drooler-fly-2.png";
  static const String drooler_fly_dead = "assets/images/drooler-fly-dead.png";
  static const String fly1 = "assets/images/fly1.png";
  static const String fly2 = "assets/images/fly2.png";
  static const String house_fly_1 = "assets/images/house-fly-1.png";
  static const String house_fly_2 = "assets/images/house-fly-2.png";
  static const String house_fly_dead = "assets/images/house-fly-dead.png";
  static const String hungry_fly_1 = "assets/images/hungry-fly-1.png";
  static const String hungry_fly_2 = "assets/images/hungry-fly-2.png";
  static const String hungry_fly_dead = "assets/images/hungry-fly-dead.png";
  static const String macho_fly_1 = "assets/images/macho-fly-1.png";
  static const String macho_fly_2 = "assets/images/macho-fly-2.png";
  static const String macho_fly_dead = "assets/images/macho-fly-dead.png";
}
