/// Generated by AssetsRefGenerator on 2021/04/03
class Res {
  static const String BagColor = "assets/BagColor.png";
  static const String FireColor = "assets/FireColor.png";
  static const String Meter = "assets/Meter.png";
  static const String off_ = "assets/off_.png";
  static const String on_ = "assets/on_.png";
  static const String on_2 = "assets/on_2.png";
  static const String Stability = "assets/Stability.png";
  static const String Stopwatch = "assets/Stopwatch.png";
  static const String tourch = "assets/tourch.png";
  static const String Vector = "assets/Vector.png";
  static const String vector_off = "assets/vector_off.png";
  static const String Weight = "assets/Weight.png";
}
